#!/usr/bin/perl
# survey
use Getopt::Std;
getopts( 'tp:i:', \my %opts );

unless( $opts{'p'} =~ m/\A((?:[A-Z0-9_]+)(?:::[A-Z0-9_]+)*)\z/i ) {
	die "Invalid package name [$opts{'p'}]\n";
	}
eval "use $1; 1";

use Surveyor::App;

if( $opts{'t'} ) {
	Surveyor::App::test( $opts{'p'}, @ARGV ) or
		die( 'Tests do not pass for $opts{p}' );
	}

$opts{'i'} = int( $opts{'i'} );

Surveyor::App::run( $opts{'p'}, int($opts{'i'}) || 10_000, @ARGV );
